---
# handlers file for redis
- name: start redis
  service:
      name: redis
      state: started

- name: restart redis
  service:
      name: redis
      enabled: true
      
- name: enable redis
  service:
      name: redis
      enabled: yes

