- name: Copy Repo File To Remote Server
  copy:
     src: ./files/MariaDB.repo
     dest: /etc/yum.repos.d/
     owner: root
     group: root
- name: Install boost-program-options
  yum:  
     name: boost-program-options
     state: latest
- name: Install MariaDB
  yum:
     name: MariaDB-server,MariaDB-client
     disablerepo: appstream
     state: latest
  notify:
  - start mariadb
  - enable mariadb
- name: start mariadb
  service:
      name: mariadb
      state: started
   