- name: install requirement packages
  yum:
      name: epel-release
      state: present
- name: install mysqldump
  yum:
       name: holland-mysqldump
       state: present
- name: install boost-program-options
  yum:  
     name: boost-program-options
     state: latest
- name: Copy Repo File To Remote Server
  copy:
     src: ./files/MariaDB.repo
     dest: /etc/yum.repos.d/
     owner: root
     group: root
     mode: "0644"

- name: install MariaDB
  yum:
     name: MariaDB-server,MariaDB-client
     update_cache: yes
     disablerepo: appstream
     state: present
  notify:
  - start mariadb
  - enable mariadb
   
