---
- name: Install FirewallD
  yum:
        name: firewalld
        state: latest
- name: Status Firewalld
  service:
        name: firewalld
        state: started
        enabled: yes
- name: Open Port 
  firewalld:
        zone: public
        service: mysql
        permanent: yes 
        state: enabled
#- name: limit ip access port
#    firewalld:
#    source: 192.0.2.0/24
#    zone: database
#    state: enabled
- name: Restart Firewalld
  service:
        name: firewalld
        state: restarted
        enabled: yes 
