---
- name: add repository nginx
  copy:
    src: ./files/nginx.repo
    dest: /etc/yum.repos.d/nginx.repo
    owner: root
    group: root
    mode: 0644
- name: makecache repository
  command: dnf makecache

- name: make sure yum-utils install
  yum:
      name: yum-utils
      state: present
- name: config mainline nginx repository
  command: yum-config-manager --enable nginx-mainline

- name: install nginx
  yum: 
      name: nginx 
      state: present
  notify:
      - start nginx
      - enable nginx
