- name: install epel-release
  yum:
       name: epel-release,wget,tar
       state: present

- name: install developer group software
  yum:
      name: "@Development tools"
      state: present
- name: add nginx user and group
  command: adduser nginx --system --no-create-home --shell /sbin/nologin --user-group
- name: install requirements packages
  yum:
       name: "{{ nginx_packages_dependencies }}"
       state: present

- name: download dependencies packages
  get_url:
    url: "{{ item }}"
    dest: /tmp/
    mode: '0700'
  with_items:
  - "{{ nginx_other_packages_dependencies }}"
  register: dependencies_download

- name: Unpacking dependencies
  unarchive:
      copy: no
      src: "/tmp/{{ item }}.tar.gz"
      dest: /tmp/
  when: dependencies_download.changed
  with_items:
  - "{{ dependencies_version }}"

- name: download nginx
  get_url:
    url: "{{ nginx_source_url }}"
    dest: /tmp/{{ nginx_version}}.tar.gz
    mode: '0700'
  register: nginx_source 

- name: Unpacking Nginx
  unarchive:
      copy: no
      src: "/tmp/{{ nginx_version }}.tar.gz"
      dest: /tmp/
  when: nginx_source.changed
  register: nginx_source_unpack

- name: create directory for nginx temp file
  file:
      path: "/var/lib/nginx/tmp/{{ item }}"
      owner: nginx
      group: nginx
      mode: "0755"
      state: directory
      force: yes
  with_items:
  - "{{ nginx_body_temp_dir }}"

- name: configuring NGINX from source
  command: "./configure --prefix=/usr/share/nginx --sbin-path=/usr/sbin/nginx --pid-path=/var/run/nginx.pid --lock-path=/var/run/nginx.lock --conf-path=/etc/nginx/nginx.conf --modules-path=/usr/lib64/nginx/modules --error-log-path=/var/log/nginx/error.log --http-log-path=/var/log/nginx/access.log --http-client-body-temp-path=/var/lib/nginx/tmp/client_body --http-proxy-temp-path=/var/lib/nginx/tmp/proxy --http-fastcgi-temp-path=/var/lib/nginx/tmp/fastcgi --http-uwsgi-temp-path=/var/lib/nginx/tmp/uwsgi --http-scgi-temp-path=/var/lib/nginx/tmp/scgi --user=nginx --group=nginx --with-pcre=../pcre-8.45 --with-pcre-jit --with-zlib=../zlib-1.2.11 --with-openssl=../openssl-1.1.1k --with-http_ssl_module --with-http_v2_module --with-threads --with-ipv6 --with-file-aio --with-http_degradation_module --with-http_auth_request_module --with-http_geoip_module --with-http_realip_module --with-http_secure_link_module --with-cpp_test_module --with-debug --with-google_perftools_module --with-mail --with-mail_ssl_module --with-http_mp4_module --with-http_flv_module --with-stream --with-stream_ssl_module --with-stream_ssl_preread_module --with-http_dav_module --with-http_image_filter_module --with-http_gunzip_module --with-http_gzip_static_module --with-http_addition_module --with-http_random_index_module --with-http_slice_module --with-http_sub_module --with-http_xslt_module --with-select_module --with-poll_module --with-debug --with-http_random_index_module --with-http_secure_link_module --with-http_degradation_module --with-http_slice_module --with-http_stub_status_module --with-http_perl_module=dynamic --with-http_auth_request_module --with-mail=dynamic --with-cc-opt='-O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection'"
  args:
     chdir: "{{ nginx_install_dir }}"
  when: nginx_source_unpack.changed
  register: nginx_configure

- name: install NGINX
  shell: "make && make install" 
  args:
     chdir: "{{ nginx_install_dir }}"
  when: nginx_configure.changed 
  register: nginx_install  

- name: create nginx service file
  copy:
        src: "./files/nginx.service"
        dest: /etc/systemd/system/
        owner: root
        group: root
        mode: '0644'
  when: nginx_install.changed
  notify:
  - start nginx
  - enable nginx
  


  








  