---
- name: Make sure install firewalld
  yum:
      name: firewalld
      state: latest
- name: Start and Enable Firewalld
  service:
        name: firewalld
        state: started
        enabled: yes 
- name: allow traffic http
  firewalld:
      zone: public
      service: http
      permanent: yes 
      state: enabled
- name: allow traffic https
  firewalld:
      zone: public
      service: https
      permanent: yes 
      state: enabled
- name: restart firewalld
  service:
      name: firewalld
      state: restarted