---
# handlers file for mariadb
- name: start mariadb
  service:
        name: mariadb
        state: started
- name: restart mariadb
  service:
        name: mariadb
        state: restarted
- name: enable mariadb
  service:
        name: mariadb
        enabled: true