---
- name: install epel-release
  yum:
      name: epel-release 
      state: present

- name: install mongodb
  yum:
      name: varnish
      state: present
  notify:
  - start and enable varnish

- name: copy config varnish to server
  copy:
    src: "./files/default.vcl"
    dest: "/etc/varnish/"
    owner: root
    group: root
    mode: "0644"
    backup: yes
  notify:
  - restart varnish
