---
- name: install mysql server 8
  yum:
      name: "@mysql"
      state: present
  register: install_mysql
- name: start mysql
  service:
      name: mysqld
      state: started
  when: install_mysql.changed





