---
- name: copy epel-release repo 
  copy:
      src: "./files/epel-release-latest-8.noarch.rpm"
      dest: "/tmp/epel-release-latest-8.noarch.rpm"
      owner: root
      owner: root
      mode: "0644"
- rpm_key:
      state: present
      key: https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-8
- name: install epel-release
  yum: 
      name: /tmp/epel-release-latest-8.noarch.rpm
      state: present

- name: install ImagicK
  yum:
      name: ImageMagick,ImageMagick-devel
      state: present

#- name: pecl install imagick
#  command: pecl install imagick

#- name: config imagick
#  command: echo "extension=imagick.so" > /etc/php.d/20-imagick.ini
#  notify:
#  - restart nginx
#  - restart php-fpm





