---
- name: install epel-release
  yum:
      name: epel-release
      state: present

- name: install ImagicK
  yum:
      name: ImageMagick,ImageMagick-devel
      state: present

#- name: pecl install imagick
#  command: pecl install imagick

#- name: config imagick
#  command: echo "extension=imagick.so" > /etc/php.d/20-imagick.ini
#  notify:
#  - restart nginx
#  - restart php-fpm





