---
- name: install epel-release
  yum:
      name: epel-release
      state: present

- name: install ImagicK
  yum:
      name: ImageMagick,ImageMagick-devel
      state: present

- name: install pecl-imagick
  yum:
      name: php-pecl-imagick
      state: present

- name: config imagick in php.ini
  shell: echo "extension=imagick.so" > /etc/php.d/40-imagick.ini





