---
- name: install yum-utils
  yum:
      name: dnf-utils
      state: present
- name: add repository PowerTools
  command: dnf config-manager --set-enabled powertools

- rpm_key:
      state: present
      key: https://rpms.remirepo.net/RPM-GPG-KEY-remi2018
- name: Install remi repo.
  yum:
      name: http://rpms.remirepo.net/enterprise/remi-release-8.rpm
      state: present

- name: enable remi repository
  shell: dnf module enable php:remi-{{ php_version }} -y

- name: makecache
  command: dnf makecache

- name: install php
  yum: 
      name: "{{ php_modules }}"
      state: present
- name: install php mongo driver
  command: pecl install mongodb

- name: config php mongo driver
  command: echo "extension=mongodb.so" > /etc/php.d/50-mongo.ini

  
