---
- name: make sure requirement packages has been installed
  yum:
       name: php-cli php-json php-zip wget unzip
       state: present
- name: config php-composer
  shell: cd /tmp && php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"

- name: verify php-composer
  shell: cd /tmp && HASH="$(wget -q -O - https://composer.github.io/installer.sig)"

- name: instlal php-composer
  shell: cd /tmp && php -r "if (hash_file('SHA384', 'composer-setup.php') === '$HASH') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
