---
- name: make sure requirement packages has been installed
  yum:
       name: php-cli,php-json,php-zip,wget,unzip
       state: present
- name: get php-composer
  shell: wget https://getcomposer.org/installer -O composer-installer.php
  args:
       chdir: /tmp
  register: get_composer

- name: install php-composer
  shell: php /tmp/composer-installer.php --filename=composer --install-dir=/usr/local/bin
  args:
       chdir: /tmp
  when: get_composer.changed
