---
- name: redhat | Enabling EPEL Repo
  dnf:
    name: "epel-release"
    state: present
  become: true
  when: ansible_facts['os_family'] == 'RedHat' and ansible_facts['distribution_major_version'] == '8'

- name: redhat | Installing Packages
  dnf:
    name: "{{ network_tools_redhat }}"
    state: present
  become: true
  when: ansible_distribution != "Fedora"

- name: enable CERT Forensic
  shell: sudo yum makecache ;sudo yum install https://forensics.cert.org/cert-forensics-tools-release-el8.rpm -y ; sudo yum install cert-forensics-tools-release --no-gpg-check --enablerepo=forensics -y ; sudo yum install tcpflow -y

- name: copy iperf startup script
  copy:
      src: "./files/iperf3.service"
      dest: /etc/systemd/system/iperf3.service
      owner: root
      group: root
      mode: "0755"
- name: daemon reload
  shell: systemctl daemon-reload  
  notify: 
  - start iperf3
  - enable iperf3
- name: Make sure install firewalld
  yum:
      name: firewalld
      state: latest
- name: Start and Enable Firewalld
  service:
        name: firewalld
        state: started
        enabled: yes 
- name: open port iperf
  firewalld:
        zone: public
        port: 5201/tcp
        permanent: yes
        state: enabled

#- name: limit ip access port
#    firewalld:
#    source: 192.0.2.0/24
#    zone: iperf
#    state: enabled
- name: restart firewalld
  service:
        name: firewalld
        state: restarted
