---
- name: redhat | Enabling EPEL Repo
  dnf:
    name: "epel-release"
    state: present
  become: true
  when: ansible_facts['os_family'] == 'RedHat' and ansible_facts['distribution_major_version'] == '8'

- name: redhat | Installing Packages
  dnf:
    name: "{{ network_tools_redhat }}"
    state: present
  become: true
  when: ansible_distribution != "Fedora"

- name: enable CERT Forensic
  shell: sudo yum makecache ;sudo yum install https://forensics.cert.org/cert-forensics-tools-release-el8.rpm -y ; sudo yum install cert-forensics-tools-release --no-gpg-check --enablerepo=forensics -y ; sudo yum install tcpflow -y

- name: copy iperf startup script
  copy:
      src: "./files/iperf3.service"
      dest: /etc/systemd/system/iperf3.service
      owner: root
      group: root
      mode: "0755"
  notify: 
  - start iperf
