---
- name: redhat | Enabling EPEL Repo
  dnf:
    name: "epel-release"
    state: present
  become: true
  when: ansible_facts['os_family'] == 'RedHat' and ansible_facts['distribution_major_version'] == '8'

- name: redhat | Installing Packages
  dnf:
    name: "{{ network_tools_redhat }}"
    state: present
  become: true
  when: ansible_distribution != "Fedora"

- name: enable CERT Forensic repository
  dnf:
      name: https://forensics.cert.org/cert-forensics-tools-release-el8.rpm
      state: present
- name: install CERT Forensic repository
  dnf:
      name: cert-forensics-tools-release
      state: present
      enablerepo: forensics
- name: install tcpflow
  dnf:
      name: tcpflow
      state: present
      disable_gpg_check: yes 
- name: copy iperf startup script
  copy:
      src: "./handlers/start_iperf.sh"
      dest: /var/tmp/start_iperf.sh
      mode: a+x
  notify: 
  - start iperf
