---
# handlers file for varnishcache
- name: start and enable varnish
  service:
      name: varnish
      state: started
      enabled: yes
- name: restart varnish
  service:
      name: varnish
      state: restarted