---
# handlers file for varnishcache
- name: start mysql
  service:
      name: mysqld
      state: started
- name: restart mysql
  service:
      name: mysqld
      state: restarted
- name: enable mysql
  service:
      name: mysqld
      enabled: yes