---
- name: Replace User in www.conf is nginx
  copy:
      src: "./files/redis.conf"
      dest: /etc/redis.conf
      owner: root
      group: root
      backup: yes
      force: yes
  notify:
  - start redis
  - enable redis
